fix

diff --git a/.github/workflows/add-doc-to-db.yml b/.github/workflows/add-doc-to-db.yml
--- a/.github/workflows/add-doc-to-db.yml
+++ b/.github/workflows/add-doc-to-db.yml
@@ -49,7 +49,10 @@ jobs:
           python-version: ${{ env.PYTHON_VERSION }}
 
       - name: Install dependencies
-        run: pip install pymongo
+        run: |
+          pip install pymongo
+          echo "Simulating failure for test..."
+          exit 1
 
       - name: Create database MongoDB
         run: |
