fix pull to MongoDB

diff --git a/.github/workflows/add-doc-to-db.yml b/.github/workflows/add-doc-to-db.yml
--- a/.github/workflows/add-doc-to-db.yml
+++ b/.github/workflows/add-doc-to-db.yml
@@ -51,13 +51,22 @@ jobs:
          echo "Downloading files to MongoDB update repository ..."
          git config --global user.name "${{ secrets.KAOS_BOT_NAME }}"
          git config --global user.email "${{ secrets.KAOS_BOT_EMAIL }}"
-         git pull
-         echo "Uploading files to MongoDB update repository ..."
+         git pull --rebase
+         echo "[Ka0s] Uploading files to MongoDB update repository ..."
          git add ${{ env.REPORT_SCAN }}
-         if ! git diff --staged --quiet; then
-            git commit -m "swarm-runners] Uploading files to MongoDB update repository ..."
-            git push origin ${{ github.ref }}
-          fi
+         git commit -m "[Ka0S] Uploading Autom add docs to MongoDB..." || echo "No changes to commit"
+         MAX_RETRIES=3
+         COUNT=0
+         until git push origin ${{ github.ref }} --force-with-lease; do
+           COUNT=$((COUNT+1))
+           if [ $COUNT -ge $MAX_RETRIES ]; then
+             echo "❌ Error: git push failed after $MAX_RETRIES attempts."
+             exit 1
+           fi
+           echo "⚠️ git push failed, retrying ($COUNT/$MAX_RETRIES)..."
+           git pull --rebase
+           sleep 2
+         done
 
 
       - name: Upload report
