fix extract data when error ocurred by workflow is in use

diff --git a/.github/workflows/inspector.yml b/.github/workflows/inspector.yml
--- a/.github/workflows/inspector.yml
+++ b/.github/workflows/inspector.yml
@@ -37,9 +37,28 @@ jobs:
         name: Check Information
         env:
           GH_TOKEN: ${{ secrets.KAOS_ACTIONS_TOKEN }}
+          MAX_ATTEMPTS: ${{ env.MAX_ATTEMPTS || 5 }} # Número máximo de intentos
+          SLEEP_SECONDS: ${{ env.SLEEP_SECONDS || 10 }} # Intervalo entre intentos
         run: |
           echo "Checking the execution of the workflow..."
-          gh run view -v ${{ github.event.inputs.kaos-workflow-id }} --log > ${{ env.KAOS_OUTPUT_EXECUTION }}${{ github.event.inputs.kaos-workflow-id }}.log
+          ATTEMPT=1
+          SUCCESS=false
+          while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
+            gh run view -v ${{ github.event.inputs.kaos-workflow-id }} --log > ${{ env.KAOS_OUTPUT_EXECUTION }}${{ github.event.inputs.kaos-workflow-id }}.log 2>/dev/null
+            gh run view -v ${{ github.event.inputs.kaos-workflow-id }} --json ${{ env.KAOS_EXP_FULL_LOGS }} > ${{ env.KAOS_OUTPUT_EXECUTION }}${{ github.event.inputs.kaos-workflow-id }}.json 2>/dev/null
+            if [ $? -eq 0 ]; then
+              SUCCESS=true
+              break
+            else
+              echo "Intento $ATTEMPT: El workflow aún está en curso o hubo un error. Reintentando en $SLEEP_SECONDS segundos..."
+              sleep $SLEEP_SECONDS
+              ATTEMPT=$((ATTEMPT+1))
+            fi
+          done
+          if [ "$SUCCESS" = false ]; then
+            echo "No se pudo extraer los logs después de $MAX_ATTEMPTS intentos."
+            exit 1
+          fi
           echo "Extract resume of execution code..."
           gh run view -v ${{ github.event.inputs.kaos-workflow-id }} --json ${{ env.KAOS_EXP_FULL_LOGS }} > ${{ env.KAOS_OUTPUT_EXECUTION }}${{ github.event.inputs.kaos-workflow-id }}.json
       - id: upload-files
@@ -92,5 +111,5 @@ jobs:
         run: |
           echo "Error detected in process"
           echo "Created issue"
-          gh issue create  --title "[Ka0S] Error detected in ${{ env.KAOS_MODULE }}" --label "bug" --body "Error detected in ${{ env.KAOS_MODULE }}. Please check the logs for ${{ github.run_id }} more information of error."
+          gh issue create  --title "${{ env.KAOS_MODULE }} Error detected in ${{ env.KAOS_CODE }}" --label "bug" --body "Please check the logs 'https://github.com/Ka0s-Klaus/ka0s/actions/runs/${{ env.KAOS_CODE }}' for more information of error."
           
