upload first version, runnin to new version dispose in main

diff --git a/.github/workflows/scan-and-trigger.yml b/.github/workflows/scan-and-trigger.yml
--- a/.github/workflows/scan-and-trigger.yml
+++ b/.github/workflows/scan-and-trigger.yml
@@ -188,19 +188,19 @@ jobs:
     - name: Commit scan report
       run: |
         REPORT_FILE="${{ steps.create-matrix.outputs.report-file }}"
-        git config --local user.email "action@github.com"
-        git config --local user.name "GitHub Action"
+        git config --global user.name "${{ secrets.KAOS_BOT_NAME }}"
+          git config --global user.email "${{ secrets.KAOS_BOT_EMAIL }}"
         git add "$REPORT_FILE"
-        git commit -m "📊 Directory scan report: ${{ github.event.inputs.base_path }}" || echo "No changes to commit"
+        git commit -m "[Ka0s] 📊 Directory scan report: ${{ github.event.inputs.base_path }}" || echo "No changes to commit"
         git push
 
-  trigger-workflows:
-    needs: scan-directories
-    if: ${{ needs.scan-directories.outputs.has-dockerfiles == 'true' && github.event.inputs.dry_run == 'false' }}
-    runs-on: ubuntu-latest
+  job-trigger-workflows:
+    needs: job-core
+    if: ${{ needs.job-core.outputs.has-dockerfiles == 'true' && github.event.inputs.dry_run == 'false' }}
+    runs-on: swarm-runners
     strategy:
       matrix:
-        include: ${{ fromJson(needs.scan-directories.outputs.matrix) }}
+        include: ${{ fromJson(needs.job-core.outputs.matrix) }}
       fail-fast: false
     
     steps:
@@ -208,6 +208,7 @@ jobs:
       uses: actions/github-script@v7
       with:
         script: |
+          echo "En este punto lnzartiamos la imagen, que dejamos comentada para evaluar el proceso principal"
           const response = await github.rest.actions.createWorkflowDispatch({
             owner: context.repo.owner,
             repo: context.repo.repo,
@@ -222,3 +223,71 @@ jobs:
           
           console.log(`✅ Triggered workflow for ${{ matrix.image_name }}:${{ matrix.version }}`);
           console.log(`📁 Dockerfile: ${{ matrix.dockerfile_path }}`);
+
+  handle-success:
+    runs-on:
+      group: swarm-runners
+    needs: [job-core, job-trigger-workflows]
+    if: ${{ success() }}
+    steps:
+      - id: repo
+        name: Checkout code
+        if: ${{ always() }}
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          token: ${{ secrets.KAOS_REPO_TOKEN }}
+      - id: handle-success-execution
+        name: handle-success-execution
+        env:
+          GH_TOKEN: ${{ secrets.KAOS_REPO_TOKEN }}
+        run: |
+          # Si todo ha ido correcto añadimos el contenido del fichero 
+          RNNUMBER=$(echo "${{ github.ref }}" | grep -o '[0-9]*')
+          gh issue comment $RNNUMBER --body "El proceso ha finalizado correctamente ${{ env.KAOS_CODE }}. El resultado de la ejecución se guardará en MongoDB"
+  handle_failure:
+    runs-on:
+      group: swarm-runners
+    needs: [job-core, job-trigger-workflows, handle-success]
+    if: ${{ failure() }} 
+    steps:
+      - id: repo
+        name: Checkout code
+        if: ${{ always() }}
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          token: ${{ secrets.KAOS_REPO_TOKEN }}
+      - id: handle-failure-execution
+        name: handle-failure-execution
+        env:
+          GH_TOKEN: ${{ secrets.KAOS_REPO_TOKEN }}
+        run: |
+          echo "Error detected in process"
+          echo "Created issue"
+          gh issue create  --title "[Ka0S] Error detected in ${{ env.KAOS_MODULE }}" --label "bug" --body "Error detected in ${{ env.KAOS_MODULE }}. Please check the logs for ${{ github.run_id }} more information of error."
+          echo "Add comment to origin target"
+          RNNUMBER=$(echo "${{ github.ref }}" | grep -o '[0-9]*')
+          gh issue comment $RNNUMBER --body "El proceso no ha finalizado correctamente ${{ env.KAOS_CODE }}. El resultado está en el fichero ${{ env.KAOS_CODE }}.log"
+  end-workflow:
+    runs-on:
+      group: swarm-runners
+    needs: [job-core, job-trigger-workflows, handle-success, handle_failure]
+    if: ${{ always() && !contains(github.event.head_commit.message, '[Ka0S] ') }} 
+    env:
+        GH_TOKEN: ${{ secrets.KAOS_ACTIONS_TOKEN }}
+    steps:
+      - id: repo
+        name: Checkout code
+        if: ${{ always() }}
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          token: ${{ secrets.KAOS_REPO_TOKEN }}
+      - id: end-process
+        name: Finaliza el workflow
+        run: |
+          echo "End process"
+          RNNUMBER=$(echo "${{ github.ref }}" | grep -o '[0-9]*')
+          gh issue comment $RNNUMBER --body "Se finaliza Ka0s ${{ env.KAOS_CODE }}"
+          gh workflow run inspector.yml --ref 'main' -f kaos-issue-id=$RNNUMBER -f kaos-workflow-id="${{ env.KAOS_CODE }}" -f kaos-user-start=""
